import { useState } from "react";
import { motion } from "framer-motion";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Sparkles, FileText, ArrowRight, ArrowLeft, Check } from "lucide-react";

interface FormData {
  clientName: string;
  clientEmail: string;
  projectTitle: string;
  industry: string;
  projectType: string;
  budget: string;
  timeline: string;
  description: string;
  deliverables: string;
  tone: string;
}

const initialForm: FormData = {
  clientName: "",
  clientEmail: "",
  projectTitle: "",
  industry: "",
  projectType: "",
  budget: "",
  timeline: "",
  description: "",
  deliverables: "",
  tone: "professional",
};

const steps = [
  { title: "Client Info", description: "Who is this proposal for?" },
  { title: "Project Details", description: "Describe the project scope" },
  { title: "Preferences", description: "Customize your proposal style" },
  { title: "Generate", description: "Review and generate your proposal" },
];

export default function ProposalGenerator() {
  const [currentStep, setCurrentStep] = useState(0);
  const [form, setForm] = useState<FormData>(initialForm);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedProposal, setGeneratedProposal] = useState<string | null>(null);

  const update = (field: keyof FormData, value: string) =>
    setForm((prev) => ({ ...prev, [field]: value }));

  const next = () => setCurrentStep((s) => Math.min(s + 1, steps.length - 1));
  const prev = () => setCurrentStep((s) => Math.max(s - 1, 0));

  const handleGenerate = async () => {
    setIsGenerating(true);
    // Simulate AI generation
    await new Promise((r) => setTimeout(r, 3000));
    setGeneratedProposal(`
# Proposal: ${form.projectTitle}

## Executive Summary
This proposal outlines a comprehensive plan for ${form.clientName} to deliver a high-quality ${form.projectType || "project"} within the ${form.industry || "technology"} sector.

## Project Scope
${form.description || "A detailed project addressing your specific needs and objectives."}

## Deliverables
${form.deliverables || "- Project deliverables as discussed\n- Documentation\n- Support & maintenance plan"}

## Timeline
Estimated completion: ${form.timeline || "To be determined"}

## Budget
Project investment: ${form.budget || "To be discussed"}

## Next Steps
1. Review and approve this proposal
2. Sign the agreement
3. Kick off the project

---
*Generated by ProposalKit AI*
    `);
    setIsGenerating(false);
  };

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <main className="pt-24 pb-16">
        <div className="container mx-auto px-4 max-w-3xl">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-center mb-12"
          >
            <div className="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-4 py-2 mb-4">
              <Sparkles className="h-4 w-4 text-primary" />
              <span className="text-sm font-medium text-primary">AI Proposal Generator</span>
            </div>
            <h1 className="font-display text-3xl sm:text-4xl font-bold mb-3">
              Create a winning <span className="text-gradient">proposal</span>
            </h1>
            <p className="text-muted-foreground max-w-lg mx-auto">
              Fill in the details and let AI craft a professional, persuasive proposal in seconds.
            </p>
          </motion.div>

          {/* Progress Steps */}
          <div className="flex items-center justify-between mb-10 max-w-md mx-auto">
            {steps.map((step, i) => (
              <div key={i} className="flex items-center">
                <div
                  className={`h-9 w-9 rounded-full flex items-center justify-center text-sm font-semibold transition-colors ${
                    i < currentStep
                      ? "bg-primary text-primary-foreground"
                      : i === currentStep
                      ? "bg-primary text-primary-foreground shadow-glow"
                      : "bg-secondary text-muted-foreground"
                  }`}
                >
                  {i < currentStep ? <Check className="h-4 w-4" /> : i + 1}
                </div>
                {i < steps.length - 1 && (
                  <div
                    className={`w-8 sm:w-12 h-0.5 mx-1 transition-colors ${
                      i < currentStep ? "bg-primary" : "bg-border"
                    }`}
                  />
                )}
              </div>
            ))}
          </div>

          {!generatedProposal ? (
            <motion.div
              key={currentStep}
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              className="rounded-xl border border-border bg-card p-6 sm:p-8"
            >
              <h2 className="font-display text-xl font-semibold mb-1 text-card-foreground">
                {steps[currentStep].title}
              </h2>
              <p className="text-sm text-muted-foreground mb-6">
                {steps[currentStep].description}
              </p>

              {currentStep === 0 && (
                <div className="space-y-5">
                  <div>
                    <Label htmlFor="clientName">Client Name</Label>
                    <Input
                      id="clientName"
                      placeholder="e.g. Acme Corp"
                      value={form.clientName}
                      onChange={(e) => update("clientName", e.target.value)}
                      className="mt-1.5"
                    />
                  </div>
                  <div>
                    <Label htmlFor="clientEmail">Client Email</Label>
                    <Input
                      id="clientEmail"
                      type="email"
                      placeholder="client@example.com"
                      value={form.clientEmail}
                      onChange={(e) => update("clientEmail", e.target.value)}
                      className="mt-1.5"
                    />
                  </div>
                  <div>
                    <Label htmlFor="industry">Industry</Label>
                    <Select value={form.industry} onValueChange={(v) => update("industry", v)}>
                      <SelectTrigger className="mt-1.5">
                        <SelectValue placeholder="Select industry" />
                      </SelectTrigger>
                      <SelectContent>
                        {["Technology", "Marketing", "Design", "Consulting", "Finance", "Healthcare", "Education", "Other"].map((ind) => (
                          <SelectItem key={ind} value={ind.toLowerCase()}>{ind}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                </div>
              )}

              {currentStep === 1 && (
                <div className="space-y-5">
                  <div>
                    <Label htmlFor="projectTitle">Project Title</Label>
                    <Input
                      id="projectTitle"
                      placeholder="e.g. Website Redesign"
                      value={form.projectTitle}
                      onChange={(e) => update("projectTitle", e.target.value)}
                      className="mt-1.5"
                    />
                  </div>
                  <div>
                    <Label htmlFor="projectType">Project Type</Label>
                    <Select value={form.projectType} onValueChange={(v) => update("projectType", v)}>
                      <SelectTrigger className="mt-1.5">
                        <SelectValue placeholder="Select type" />
                      </SelectTrigger>
                      <SelectContent>
                        {["Web Development", "Mobile App", "Brand Identity", "Marketing Campaign", "Consulting", "UI/UX Design", "Other"].map((t) => (
                          <SelectItem key={t} value={t.toLowerCase()}>{t}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label htmlFor="description">Project Description</Label>
                    <Textarea
                      id="description"
                      placeholder="Describe the project goals, requirements, and any special considerations..."
                      rows={4}
                      value={form.description}
                      onChange={(e) => update("description", e.target.value)}
                      className="mt-1.5"
                    />
                  </div>
                  <div>
                    <Label htmlFor="deliverables">Key Deliverables</Label>
                    <Textarea
                      id="deliverables"
                      placeholder="List the main deliverables, one per line..."
                      rows={3}
                      value={form.deliverables}
                      onChange={(e) => update("deliverables", e.target.value)}
                      className="mt-1.5"
                    />
                  </div>
                </div>
              )}

              {currentStep === 2 && (
                <div className="space-y-5">
                  <div>
                    <Label htmlFor="budget">Budget Range</Label>
                    <Select value={form.budget} onValueChange={(v) => update("budget", v)}>
                      <SelectTrigger className="mt-1.5">
                        <SelectValue placeholder="Select budget range" />
                      </SelectTrigger>
                      <SelectContent>
                        {["$500 - $1,000", "$1,000 - $5,000", "$5,000 - $10,000", "$10,000 - $25,000", "$25,000 - $50,000", "$50,000+"].map((b) => (
                          <SelectItem key={b} value={b}>{b}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label htmlFor="timeline">Timeline</Label>
                    <Select value={form.timeline} onValueChange={(v) => update("timeline", v)}>
                      <SelectTrigger className="mt-1.5">
                        <SelectValue placeholder="Select timeline" />
                      </SelectTrigger>
                      <SelectContent>
                        {["1 - 2 weeks", "2 - 4 weeks", "1 - 2 months", "2 - 3 months", "3 - 6 months", "6+ months"].map((t) => (
                          <SelectItem key={t} value={t}>{t}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label htmlFor="tone">Proposal Tone</Label>
                    <Select value={form.tone} onValueChange={(v) => update("tone", v)}>
                      <SelectTrigger className="mt-1.5">
                        <SelectValue placeholder="Select tone" />
                      </SelectTrigger>
                      <SelectContent>
                        {[
                          { value: "professional", label: "Professional & Formal" },
                          { value: "friendly", label: "Friendly & Approachable" },
                          { value: "bold", label: "Bold & Confident" },
                          { value: "minimal", label: "Minimal & Direct" },
                        ].map((t) => (
                          <SelectItem key={t.value} value={t.value}>{t.label}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                </div>
              )}

              {currentStep === 3 && (
                <div className="space-y-4">
                  <h3 className="font-display text-lg font-semibold text-card-foreground">Review Your Details</h3>
                  <div className="grid sm:grid-cols-2 gap-4">
                    {[
                      { label: "Client", value: form.clientName || "—" },
                      { label: "Email", value: form.clientEmail || "—" },
                      { label: "Project", value: form.projectTitle || "—" },
                      { label: "Industry", value: form.industry || "—" },
                      { label: "Type", value: form.projectType || "—" },
                      { label: "Budget", value: form.budget || "—" },
                      { label: "Timeline", value: form.timeline || "—" },
                      { label: "Tone", value: form.tone || "—" },
                    ].map((item) => (
                      <div key={item.label} className="rounded-lg bg-secondary/50 p-3">
                        <div className="text-xs text-muted-foreground font-mono uppercase tracking-wider">{item.label}</div>
                        <div className="text-sm font-medium text-card-foreground mt-0.5 capitalize">{item.value}</div>
                      </div>
                    ))}
                  </div>
                  {form.description && (
                    <div className="rounded-lg bg-secondary/50 p-3">
                      <div className="text-xs text-muted-foreground font-mono uppercase tracking-wider">Description</div>
                      <div className="text-sm text-card-foreground mt-0.5">{form.description}</div>
                    </div>
                  )}
                </div>
              )}

              {/* Navigation */}
              <div className="flex justify-between mt-8">
                <Button
                  variant="ghost"
                  onClick={prev}
                  disabled={currentStep === 0}
                  className="gap-2"
                >
                  <ArrowLeft className="h-4 w-4" /> Back
                </Button>
                {currentStep < steps.length - 1 ? (
                  <Button variant="hero" onClick={next} className="gap-2">
                    Next <ArrowRight className="h-4 w-4" />
                  </Button>
                ) : (
                  <Button
                    variant="hero"
                    onClick={handleGenerate}
                    disabled={isGenerating}
                    className="gap-2"
                  >
                    {isGenerating ? (
                      <>
                        <motion.div
                          animate={{ rotate: 360 }}
                          transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                        >
                          <Sparkles className="h-4 w-4" />
                        </motion.div>
                        Generating...
                      </>
                    ) : (
                      <>
                        <Sparkles className="h-4 w-4" /> Generate Proposal
                      </>
                    )}
                  </Button>
                )}
              </div>
            </motion.div>
          ) : (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="space-y-6"
            >
              <div className="flex items-center justify-between">
                <h2 className="font-display text-xl font-semibold text-foreground flex items-center gap-2">
                  <FileText className="h-5 w-5 text-primary" />
                  Your Proposal
                </h2>
                <div className="flex gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => {
                      setGeneratedProposal(null);
                      setCurrentStep(0);
                      setForm(initialForm);
                    }}
                  >
                    Start Over
                  </Button>
                  <Button variant="hero" size="sm" onClick={() => navigator.clipboard.writeText(generatedProposal)}>
                    Copy to Clipboard
                  </Button>
                </div>
              </div>
              <div className="rounded-xl border border-border bg-card p-6 sm:p-8">
                <pre className="whitespace-pre-wrap font-body text-sm text-card-foreground leading-relaxed">
                  {generatedProposal}
                </pre>
              </div>
            </motion.div>
          )}
        </div>
      </main>
      <Footer />
    </div>
  );
}
